### ISSUE TITLE
Nomad cannot pull images

### ISSUE THREAD

**Issue by nathanjent** [visibilityspots/nomad-local-development#2]
Images are failing to pull when running the infrastructure setup. The nomad docker driver runs under the 'nomad' user which doesn't have permissions to access docker. Adding the 'nomad' user in the 'docker' group during the Vagrant initialization should fix this. https://www.nomadproject.io/docs/drivers/docker#client-requirements

**Comment by visibilityspots** [comment]
Taking a quick look into the project again and as I thought the nomad daemon runs as root. It's just a development machine so this wouldn't harm..
I did a vagrant up and could without any issue spin up the cadvisor job from within the nomad directory in this repository..
Could you elaborate how you start a job?

**Comment by nathanjent** [comment]
I ran it again and you are correct. It may have been a network issue with my LXC setup.
